[[main]]
  name = "Career"
  pageRef = "career"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 30

[[main]]
  name = "Resume"
  pageRef = "resume"
  weight = 40

[[main]]
  name = "Study"
  pageRef = "study"
  weight = 50

[[main]]
  name = "Hobby"
  pageRef = "hobby"
  weight = 60

[[main]]
  name = ""
  pre = "github"
  url = "https://github.com/juseok1729"
  weight = 65

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20
